--- #YAML:1.0
name:               Email-MIME-ContentType
version:            1.015
abstract:           Parse a MIME Content-Type Header
author:
    - Simon Cozens <simon@nonet>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    Repository:  http://github.com/rjbs/email-mime-contenttype
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
