#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-ContentType
version:      1.0
version_from: ContentType.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
